# **Content-based Course Recommender System Using User Profile and Course Genres**

## Prepare and setup the lab environment

In [ ]:
%pip install scikit-learn
%pip install pandas

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [ ]:
# also set a random state
rs = 123

### Lets generate user profiles using course genres and ratings

In [ ]:
course_genres = ['Python', 'Database', 'MachineLearning']
courses = [['Machine Learning with Python', 1, 0, 1], ["SQL with Python", 1, 1, 0]]
courses_df = pd.DataFrame(courses, columns = ['Title'] + course_genres)
courses_df

                          Title  Python  Database  MachineLearning
0  Machine Learning with Python       1         0                1
1               SQL with Python       1         1                0

In [ ]:
users = [['user0', 'Machine Learning with Python', 3], ['user1', 'SQL with Python', 2]]
users_df = pd.DataFrame(users, columns = ['User', 'Title', 'Rating'])
users_df

    User                         Title  Rating
0  user0  Machine Learning with Python       3
1  user1               SQL with Python       2

In [ ]:
# User 0 rated course 0 as 3 and course 1 as 0/NA (unknown or not interested)
u0 = np.array([[3, 0]])

In [ ]:
# The course genre's matrix
C = courses_df[['Python', 'Database', 'MachineLearning']].to_numpy()

In [ ]:
print(f"User profile vector shape {u0.shape} and course genre matrix shape {C.shape}")

User profile vector shape (1, 2) and course genre matrix shape (2, 3)

In [ ]:
u0_weights = np.matmul(u0, C)
u0_weights

array([[3, 0, 3]])

In [ ]:
course_genres

['Python', 'Database', 'MachineLearning']

In [ ]:
# User 1 rated course 0 as 0 (unknown or not interested) and course 1 as 2
u1 = np.array([[0, 2]])

In [ ]:
u1_weights = np.matmul(u1, C)
u1_weights

array([[2, 2, 0]])

In [ ]:
weights = np.concatenate((u0_weights.reshape(1, 3), u1_weights.reshape(1, 3)), axis=0)
profiles_df = pd.DataFrame(weights, columns=['Python', 'Database', 'MachineLearning'])
profiles_df.insert(0, 'user', ['user0', 'user1'])

In [ ]:
profiles_df

    user  Python  Database  MachineLearning
0  user0       3         0                3
1  user1       2         2                0

### Generate recommendation scores for some new courses

In [ ]:
new_courses = [['Python 101', 1, 0, 0], ["Database 101", 0, 1, 0], ["Machine Learning with R", 0, 0, 1]]
new_courses_df = pd.DataFrame(new_courses, columns = ['Title', 'Python', 'Database', 'MachineLearning'])
new_courses_df

                     Title  Python  Database  MachineLearning
0               Python 101       1         0                0
1             Database 101       0         1                0
2  Machine Learning with R       0         0                1

In [ ]:
profiles_df

    user  Python  Database  MachineLearning
0  user0       3         0                3
1  user1       2         2                0

In [ ]:
# Drop the title column
new_courses_df = new_courses_df.loc[:, new_courses_df.columns != 'Title']
course_matrix = new_courses_df.values
course_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# course matrix shape
course_matrix.shape

(3, 3)

In [ ]:
# Drop the user column
profiles_df = profiles_df.loc[:, profiles_df.columns != 'user']
profile_matrix = profiles_df.values
profile_matrix

array([[3, 0, 3],
       [2, 2, 0]])

In [ ]:
profile_matrix.shape

(2, 3)

In [ ]:
scores = np.matmul(course_matrix, profile_matrix.T)
scores

array([[3, 2],
       [0, 2],
       [3, 0]])

In [ ]:
scores_df = pd.DataFrame(scores, columns=['User0', 'User1'])
scores_df.index = ['Python 101', 'Database 101', 'Machine Learning with R']

In [ ]:
# recommendation score dataframe
scores_df

                         User0  User1
Python 101                   3      2
Database 101                 0      2
Machine Learning with R      3      0

### TASK: Generate course recommendations based on user profile and course genre vectors

In [ ]:
course_genre_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/course_genre.csv"
course_genres_df = pd.read_csv(course_genre_url)

In [ ]:
course_genres_df.head()

,COURSE_ID,TITLE,Database,Python,CloudComputing,DataAnalysis,Containers,MachineLearning,ComputerVision,DataScience,BigData,Chatbot,R,BackendDev,FrontendDev,Blockchain
0,ML0201EN,robots are coming build iot apps with watson ...,0,0,0,0,0,0,0,0,0,0,0,1,1,0
1,ML0122EN,accelerating deep learning with gpu,0,1,0,0,0,1,0,1,0,0,0,0,0,0
2,GPXX0ZG0EN,consuming restful services using the reactive ...,0,0,0,0,0,0,0,0,0,0,0,1,1,0
3,RP0105EN,analyzing big data in r using apache spark,1,0,0,1,0,0,0,0,1,0,1,0,0,0
4,GPXX0Z2PEN,containerizing packaging and running a sprin...,0,0,0,0,1,0,0,0,0,0,0,1,0,0

In [ ]:
profile_genre_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/user_profile.csv"
profile_df = pd.read_csv(profile_genre_url)

In [ ]:
profile_df.head()

,user,Database,Python,CloudComputing,DataAnalysis,Containers,MachineLearning,ComputerVision,DataScience,BigData,Chatbot,R,BackendDev,FrontendDev,Blockchain
0,2,52.0,14.0,6.0,43.0,3.0,33.0,0.0,29.0,41.0,2.0,18.0,34.0,9.0,6.0
1,4,40.0,2.0,4.0,28.0,0.0,14.0,0.0,20.0,24.0,0.0,6.0,6.0,0.0,2.0
2,5,24.0,8.0,18.0,24.0,0.0,30.0,0.0,22.0,14.0,2.0,14.0,26.0,4.0,6.0
3,7,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
4,8,6.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,0.0,2.0,0.0,0.0,0.0

In [ ]:
profile_df[profile_df['user'] == 8]

,user,Database,Python,CloudComputing,DataAnalysis,Containers,MachineLearning,ComputerVision,DataScience,BigData,Chatbot,R,BackendDev,FrontendDev,Blockchain
4,8,6.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,0.0,2.0,0.0,0.0,0.0

In [ ]:
test_users_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMSkillsNetwork-ML0321EN-Coursera/labs/v2/module_3/ratings.csv"
test_users_df = pd.read_csv(test_users_url)

In [ ]:
test_users_df.head()

      user        item  rating
0  1889878    CC0101EN       5
1  1342067    CL0101EN       3
2  1990814  ML0120ENv3       5
3   380098    BD0211EN       5
4   779563    DS0101EN       3

In [ ]:
# Group the test users DataFrame by the 'user' column and find the maximum value for each group,
# then reset the index and drop the old index to obtain a DataFrame with unique user IDs
test_users = test_users_df.groupby(['user']).max().reset_index(drop=False)

# Extract the 'user' column from the test_users DataFrame and convert it to a list of user IDs
test_user_ids = test_users['user'].to_list()

# Print the total number of test users by obtaining the length of the test_user_ids list
print(f"Total numbers of test users {len(test_user_ids)}")

Total numbers of test users 33901

In [ ]:
test_user_profile = profile_df[profile_df['user'] == 1078030]
test_user_profile

,user,Database,Python,CloudComputing,DataAnalysis,Containers,MachineLearning,ComputerVision,DataScience,BigData,Chatbot,R,BackendDev,FrontendDev,Blockchain
18204,1078030,0.0,12.0,0.0,9.0,0.0,12.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Now let's get the test user vector by excluding the `user` column
test_user_vector = test_user_profile.iloc[0, 1:].values
test_user_vector# Now let's get the test user vector by excluding the `user` column
test_user_vector = test_user_profile.iloc[0, 1:].values
test_user_vector# Now let's get the test user vector by excluding the `user` column
test_user_vector = test_user_profile.iloc[0, 1:].values
test_user_vector

array([ 0., 12.,  0.,  9.,  0., 12.,  0.,  6.,  0.,  0.,  0.,  0.,  0.,
        0.])

In [ ]:
enrolled_courses = test_users_df[test_users_df['user'] == 1078030]['item'].to_list()
enrolled_courses = set(enrolled_courses)

In [ ]:
enrolled_courses

{'DA0101EN',
 'DV0101EN',
 'ML0101ENv3',
 'ML0115EN',
 'ML0120ENv2',
 'ML0122ENv1',
 'PY0101EN',
 'ST0101EN'}

In [ ]:
all_courses = set(course_genres_df['COURSE_ID'].values)
all_courses

{'AI0111EN',
 'BC0101EN',
 'BC0201EN',
 'BC0202EN',
 'BD0101EN',
 'BD0111EN',
 'BD0115EN',
 'BD0121EN',
 'BD0123EN',
 'BD0131EN',
 'BD0133EN',
 'BD0135EN',
 'BD0137EN',
 'BD0141EN',
 'BD0143EN',
 'BD0145EN',
 'BD0151EN',
 'BD0153EN',
 'BD0211EN',
 'BD0212EN',
 'BD0221EN',
 'BD0223EN',
 'BENTEST4',
 'CB0101EN',
 'CB0103EN',
 'CB0105ENv1',
 'CB0201EN',
 'CC0101EN',
 'CC0103EN',
 'CC0120EN',
 'CC0121EN',
 'CC0150EN',
 'CC0201EN',
 'CC0210EN',
 'CC0250EN',
 'CC0271EN',
 'CL0101EN',
 'CNSC02EN',
 'CO0101EN',
 'CO0193EN',
 'CO0201EN',
 'CO0301EN',
 'CO0302EN',
 'CO0401EN',
 'COM001EN',
 'CP0101EN',
 'DA0101EN',
 'DA0151EN',
 'DA0201EN',
 'DAI101EN',
 'DB0101EN',
 'DB0111EN',
 'DB0113EN',
 'DB0115EN',
 'DB0151EN',
 'DE0205EN',
 'DJ0101EN',
 'DP0101EN',
 'DS0101EN',
 'DS0103EN',
 'DS0105EN',
 'DS0107',
 'DS0110EN',
 'DS0132EN',
 'DS0201EN',
 'DS0301EN',
 'DS0321EN',
 'DV0101EN',
 'DV0151EN',
 'DW0101EN',
 'DX0106EN',
 'DX0107EN',
 'DX0108EN',
 'EE0101EN',
 'GPXX01AVEN',
 'GPXX01DCEN',
 'GPXX01RYEN',
 'GPXX03HFEN',
 'GPXX0435EN',
 'GPXX048OEN',
 'GPXX04HEEN',
 'GPXX04MXEN',
 'GPXX04P5EN',
 'GPXX04TNEN',
 'GPXX04V3EN',
 'GPXX04XJEN',
 'GPXX05LMEN',
 'GPXX05P1EN',
 'GPXX05RDEN',
 'GPXX06KEEN',
 'GPXX06RFEN',
 'GPXX06ZLEN',
 'GPXX0725EN',
 'GPXX0742EN',
 'GPXX07REN',
 'GPXX07UGEN',
 'GPXX07YGEN',
 'GPXX08WYEN',
 'GPXX097UEN',
 'GPXX0A1YEN',
 'GPXX0ADEN',
 'GPXX0BSAEN',
 'GPXX0BUBEN',
 'GPXX0D14EN',
 'GPXX0E3QEN',
 'GPXX0FFCEN',
 'GPXX0FTCEN',
 'GPXX0G31EN',
 'GPXX0G3KEN',
 'GPXX0G81EN',
 'GPXX0HAAEN',
 'GPXX0HC7EN',
 'GPXX0HZ2EN',
 'GPXX0I4FEN',
 'GPXX0IBEN',
 'GPXX0IHMEN',
 'GPXX0JGFEN',
 'GPXX0JLHEN',
 'GPXX0JZ4EN',
 'GPXX0KHHEN',
 'GPXX0KV4EN',
 'GPXX0KY1EN',
 'GPXX0LLEEN',
 'GPXX0M6UEN',
 'GPXX0M7ZEN',
 'GPXX0MIIEN',
 'GPXX0MP0EN',
 'GPXX0NHZEN',
 'GPXX0PG8EN',
 'GPXX0PICEN',
 'GPXX0Q8AEN',
 'GPXX0QJFEN',
 'GPXX0QQ3EN',
 'GPXX0QR3EN',
 'GPXX0QS6EN',
 'GPXX0QTEEN',
 'GPXX0QU9EN',
 'GPXX0RL8EN',
 'GPXX0RQLEN',
 'GPXX0SDXEN',
 'GPXX0T0FEN',
 'GPXX0T3CEN',
 'GPXX0TY1EN',
 'GPXX0UMSEN',
 'GPXX0UN5EN',
 'GPXX0W7KEN',
 'GPXX0WRDEN',
 'GPXX0WTIEN',
 'GPXX0XENEN',
 'GPXX0XFQEN',
 'GPXX0XV3EN',
 'GPXX0YBFEN',
 'GPXX0YMEEN',
 'GPXX0YXHEN',
 'GPXX0Z2PEN',
 'GPXX0ZG0EN',
 'GPXX0ZMZEN',
 'GPXX0ZYVEN',
 'HCC104EN',
 'HCC105EN',
 'IT0101EN',
 'LB0101ENv1',
 'LB0103ENv1',
 'LB0105ENv1',
 'LB0107ENv1',
 'LB0109ENv1',
 'LB0111EN',
 'ML0101EN',
 'ML0101ENv3',
 'ML0103EN',
 'ML0109EN',
 'ML0111EN',
 'ML0115EN',
 'ML0120EN',
 'ML0120ENv2',
 'ML0120ENv3',
 'ML0122EN',
 'ML0122ENv1',
 'ML0122ENv3',
 'ML0151EN',
 'ML0201EN',
 'OS0101EN',
 'PA0101EN',
 'PA0103EN',
 'PA0107EN',
 'PA0109EN',
 'PHPM002EN',
 'PY0101EN',
 'QC0101EN',
 'RAVSCTEST1',
 'RP0101EN',
 'RP0103',
 'RP0103EN',
 'RP0105EN',
 'RP0151EN',
 'SC0101EN',
 'SC0103EN',
 'SC0105EN',
 'SECM03EN',
 'SN0111EN',
 'ST0101EN',
 'ST0201EN',
 'ST0301EN',
 'SW0101EN',
 'SW0201EN',
 'TA0105',
 'TA0105EN',
 'TA0106EN',
 'TMP0101EN',
 'TMP0105EN',
 'TMP0106',
 'TMP107',
 'WA0101EN',
 'WA0103EN',
 'excourse01',
 'excourse02',
 'excourse03',
 'excourse04',
 'excourse05',
 'excourse06',
 'excourse07',
 'excourse08',
 'excourse09',
 'excourse10',
 'excourse11',
 'excourse12',
 'excourse13',
 'excourse14',
 'excourse15',
 'excourse16',
 'excourse17',
 'excourse18',
 'excourse19',
 'excourse20',
 'excourse21',
 'excourse22',
 'excourse23',
 'excourse24',
 'excourse25',
 'excourse26',
 'excourse27',
 'excourse28',
 'excourse29',
 'excourse30',
 'excourse31',
 'excourse32',
 'excourse33',
 'excourse34',
 'excourse35',
 'excourse36',
 'excourse37',
 'excourse38',
 'excourse39',
 'excourse40',
 'excourse41',
 'excourse42',
 'excourse43',
 'excourse44',
 'excourse45',
 'excourse46',
 'excourse47',
 'excourse48',
 'excourse49',
 'excourse50',
 'excourse51',
 'excourse52',
 'excourse53',
 'excourse54',
 'excourse55',
 'excourse56',
 'excourse57',
 'excourse58',
 'excourse59',
 'excourse60',
 'excourse61',
 'excourse62',
 'excourse63',
 'excourse64',
 'excourse65',
 'excourse66',
 'excourse67',
 'excourse68',
 'excourse69',
 'excourse70',
 'excourse71',
 'excourse72',
 'excourse73',
 'excourse74',
 'excourse75',
 'excourse76',
 'excourse77',
 'excourse78',
 'excourse79',
 'excourse80',
 'excourse81',
 'excourse82',
 'excourse83',
 'excourse84',
 'excourse85',
 'excourse86',
 'excourse87',
 'excourse88',
 'excourse89',
 'excourse90',
 'excourse91',
 'excourse92',
 'excourse93'}

In [ ]:
unknown_courses = all_courses.difference(enrolled_courses)
unknown_courses

{'AI0111EN',
 'BC0101EN',
 'BC0201EN',
 'BC0202EN',
 'BD0101EN',
 'BD0111EN',
 'BD0115EN',
 'BD0121EN',
 'BD0123EN',
 'BD0131EN',
 'BD0133EN',
 'BD0135EN',
 'BD0137EN',
 'BD0141EN',
 'BD0143EN',
 'BD0145EN',
 'BD0151EN',
 'BD0153EN',
 'BD0211EN',
 'BD0212EN',
 'BD0221EN',
 'BD0223EN',
 'BENTEST4',
 'CB0101EN',
 'CB0103EN',
 'CB0105ENv1',
 'CB0201EN',
 'CC0101EN',
 'CC0103EN',
 'CC0120EN',
 'CC0121EN',
 'CC0150EN',
 'CC0201EN',
 'CC0210EN',
 'CC0250EN',
 'CC0271EN',
 'CL0101EN',
 'CNSC02EN',
 'CO0101EN',
 'CO0193EN',
 'CO0201EN',
 'CO0301EN',
 'CO0302EN',
 'CO0401EN',
 'COM001EN',
 'CP0101EN',
 'DA0151EN',
 'DA0201EN',
 'DAI101EN',
 'DB0101EN',
 'DB0111EN',
 'DB0113EN',
 'DB0115EN',
 'DB0151EN',
 'DE0205EN',
 'DJ0101EN',
 'DP0101EN',
 'DS0101EN',
 'DS0103EN',
 'DS0105EN',
 'DS0107',
 'DS0110EN',
 'DS0132EN',
 'DS0201EN',
 'DS0301EN',
 'DS0321EN',
 'DV0151EN',
 'DW0101EN',
 'DX0106EN',
 'DX0107EN',
 'DX0108EN',
 'EE0101EN',
 'GPXX01AVEN',
 'GPXX01DCEN',
 'GPXX01RYEN',
 'GPXX03HFEN',
 'GPXX0435EN',
 'GPXX048OEN',
 'GPXX04HEEN',
 'GPXX04MXEN',
 'GPXX04P5EN',
 'GPXX04TNEN',
 'GPXX04V3EN',
 'GPXX04XJEN',
 'GPXX05LMEN',
 'GPXX05P1EN',
 'GPXX05RDEN',
 'GPXX06KEEN',
 'GPXX06RFEN',
 'GPXX06ZLEN',
 'GPXX0725EN',
 'GPXX0742EN',
 'GPXX07REN',
 'GPXX07UGEN',
 'GPXX07YGEN',
 'GPXX08WYEN',
 'GPXX097UEN',
 'GPXX0A1YEN',
 'GPXX0ADEN',
 'GPXX0BSAEN',
 'GPXX0BUBEN',
 'GPXX0D14EN',
 'GPXX0E3QEN',
 'GPXX0FFCEN',
 'GPXX0FTCEN',
 'GPXX0G31EN',
 'GPXX0G3KEN',
 'GPXX0G81EN',
 'GPXX0HAAEN',
 'GPXX0HC7EN',
 'GPXX0HZ2EN',
 'GPXX0I4FEN',
 'GPXX0IBEN',
 'GPXX0IHMEN',
 'GPXX0JGFEN',
 'GPXX0JLHEN',
 'GPXX0JZ4EN',
 'GPXX0KHHEN',
 'GPXX0KV4EN',
 'GPXX0KY1EN',
 'GPXX0LLEEN',
 'GPXX0M6UEN',
 'GPXX0M7ZEN',
 'GPXX0MIIEN',
 'GPXX0MP0EN',
 'GPXX0NHZEN',
 'GPXX0PG8EN',
 'GPXX0PICEN',
 'GPXX0Q8AEN',
 'GPXX0QJFEN',
 'GPXX0QQ3EN',
 'GPXX0QR3EN',
 'GPXX0QS6EN',
 'GPXX0QTEEN',
 'GPXX0QU9EN',
 'GPXX0RL8EN',
 'GPXX0RQLEN',
 'GPXX0SDXEN',
 'GPXX0T0FEN',
 'GPXX0T3CEN',
 'GPXX0TY1EN',
 'GPXX0UMSEN',
 'GPXX0UN5EN',
 'GPXX0W7KEN',
 'GPXX0WRDEN',
 'GPXX0WTIEN',
 'GPXX0XENEN',
 'GPXX0XFQEN',
 'GPXX0XV3EN',
 'GPXX0YBFEN',
 'GPXX0YMEEN',
 'GPXX0YXHEN',
 'GPXX0Z2PEN',
 'GPXX0ZG0EN',
 'GPXX0ZMZEN',
 'GPXX0ZYVEN',
 'HCC104EN',
 'HCC105EN',
 'IT0101EN',
 'LB0101ENv1',
 'LB0103ENv1',
 'LB0105ENv1',
 'LB0107ENv1',
 'LB0109ENv1',
 'LB0111EN',
 'ML0101EN',
 'ML0103EN',
 'ML0109EN',
 'ML0111EN',
 'ML0120EN',
 'ML0120ENv3',
 'ML0122EN',
 'ML0122ENv3',
 'ML0151EN',
 'ML0201EN',
 'OS0101EN',
 'PA0101EN',
 'PA0103EN',
 'PA0107EN',
 'PA0109EN',
 'PHPM002EN',
 'QC0101EN',
 'RAVSCTEST1',
 'RP0101EN',
 'RP0103',
 'RP0103EN',
 'RP0105EN',
 'RP0151EN',
 'SC0101EN',
 'SC0103EN',
 'SC0105EN',
 'SECM03EN',
 'SN0111EN',
 'ST0201EN',
 'ST0301EN',
 'SW0101EN',
 'SW0201EN',
 'TA0105',
 'TA0105EN',
 'TA0106EN',
 'TMP0101EN',
 'TMP0105EN',
 'TMP0106',
 'TMP107',
 'WA0101EN',
 'WA0103EN',
 'excourse01',
 'excourse02',
 'excourse03',
 'excourse04',
 'excourse05',
 'excourse06',
 'excourse07',
 'excourse08',
 'excourse09',
 'excourse10',
 'excourse11',
 'excourse12',
 'excourse13',
 'excourse14',
 'excourse15',
 'excourse16',
 'excourse17',
 'excourse18',
 'excourse19',
 'excourse20',
 'excourse21',
 'excourse22',
 'excourse23',
 'excourse24',
 'excourse25',
 'excourse26',
 'excourse27',
 'excourse28',
 'excourse29',
 'excourse30',
 'excourse31',
 'excourse32',
 'excourse33',
 'excourse34',
 'excourse35',
 'excourse36',
 'excourse37',
 'excourse38',
 'excourse39',
 'excourse40',
 'excourse41',
 'excourse42',
 'excourse43',
 'excourse44',
 'excourse45',
 'excourse46',
 'excourse47',
 'excourse48',
 'excourse49',
 'excourse50',
 'excourse51',
 'excourse52',
 'excourse53',
 'excourse54',
 'excourse55',
 'excourse56',
 'excourse57',
 'excourse58',
 'excourse59',
 'excourse60',
 'excourse61',
 'excourse62',
 'excourse63',
 'excourse64',
 'excourse65',
 'excourse66',
 'excourse67',
 'excourse68',
 'excourse69',
 'excourse70',
 'excourse71',
 'excourse72',
 'excourse73',
 'excourse74',
 'excourse75',
 'excourse76',
 'excourse77',
 'excourse78',
 'excourse79',
 'excourse80',
 'excourse81',
 'excourse82',
 'excourse83',
 'excourse84',
 'excourse85',
 'excourse86',
 'excourse87',
 'excourse88',
 'excourse89',
 'excourse90',
 'excourse91',
 'excourse92',
 'excourse93'}

In [ ]:
unknown_course_genres = course_genres_df[course_genres_df['COURSE_ID'].isin(unknown_courses)]
# Now let's get the course matrix by excluding `COURSE_ID` and `TITLE` columns:
course_matrix = unknown_course_genres.iloc[:, 2:].values
course_matrix

array([[0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 1, 0]])

In [ ]:
score = np.dot(course_matrix[1], test_user_vector)
score

np.float64(30.0)

In [ ]:
# Reload the test users dataset from the specified URL using pandas and store it in test_users_df
test_users_df = pd.read_csv(test_users_url)

# Reload the user profiles dataset from the specified URL containing user profiles and their associated genres using pandas and store it in profile_df
profile_df = pd.read_csv(profile_genre_url)

# Reload the course genres dataset from the specified URL containing course genres using pandas and store it in course_genres_df
course_genres_df = pd.read_csv(course_genre_url)

# Create an empty dictionary to store the results of the recommendation process
res_dict = {}
# Reload the test users dataset from the specified URL using pandas and store it in test_users_df
test_users_df = pd.read_csv(test_users_url)

# Reload the user profiles dataset from the specified URL containing user profiles and their associated genres using pandas and store it in profile_df
profile_df = pd.read_csv(profile_genre_url)

# Reload the course genres dataset from the specified URL containing course genres using pandas and store it in course_genres_df
course_genres_df = pd.read_csv(course_genre_url)

# Create an empty dictionary to store the results of the recommendation process
res_dict = {}
# Reload the test users dataset from the specified URL using pandas and store it in test_users_df
test_users_df = pd.read_csv(test_users_url)

# Reload the user profiles dataset from the specified URL containing user profiles and their associated genres using pandas and store it in profile_df
profile_df = pd.read_csv(profile_genre_url)

# Reload the course genres dataset from the specified URL containing course genres using pandas and store it in course_genres_df
course_genres_df = pd.read_csv(course_genre_url)

# Create an empty dictionary to store the results of the recommendation process
res_dict = {}

In [ ]:
# Only keep the score larger than the recommendation threshold
# The threshold can be fine-tuned to adjust the size of generated recommendations
score_threshold = 10.0

In [ ]:
def generate_recommendation_scores():
    """
    Generate recommendation scores for users and courses.

    Returns:
    users (list): List of user IDs.
    courses (list): List of recommended course IDs.
    scores (list): List of recommendation scores.
    """

    users = []      # List to store user IDs
    courses = []    # List to store recommended course IDs
    scores = []     # List to store recommendation scores

    # Iterate over each user ID in the test_user_ids list
    for user_id in test_user_ids:
        # Get the user profile data for the current user
        test_user_profile = profile_df[profile_df['user'] == user_id]

        # Get the user vector for the current user id (replace with your method to obtain the user vector)
        test_user_vector = test_user_profile.iloc[0, 1:].values

        # Get the known course ids for the current user
        enrolled_courses = test_users_df[test_users_df['user'] == user_id]['item'].to_list()

        # Calculate the unknown course ids
        unknown_courses = all_courses.difference(enrolled_courses)

        # Filter the course_genres_df to include only unknown courses
        unknown_course_df = course_genres_df[course_genres_df['COURSE_ID'].isin(unknown_courses)]
        unknown_course_ids = unknown_course_df['COURSE_ID'].values

        # Calculate the recommendation scores using dot product
        recommendation_scores = np.dot(unknown_course_df.iloc[:, 2:].values, test_user_vector)

        # Append the results into the users, courses, and scores list
        for i in range(0, len(unknown_course_ids)):
            score = recommendation_scores[i]

            # Only keep the courses with high recommendation score
            if score >= score_threshold:
                users.append(user_id)
                courses.append(unknown_course_ids[i])
                scores.append(recommendation_scores[i])

    return users, courses, scores

In [ ]:
# Call the generate_recommendation_scores function to obtain recommendation scores for users and courses,
# and assign the returned lists to variables users, courses, and scores
users, courses, scores = generate_recommendation_scores()

# Create an empty dictionary named res_dict to store the results of the recommendation process
res_dict = {}

# Store the lists of users, courses, and scores into the res_dict dictionary with corresponding keys
res_dict['USER'] = users
res_dict['COURSE_ID'] = courses
res_dict['SCORE'] = scores

# Create a DataFrame named res_df using the res_dict dictionary, specifying the column order as ['USER', 'COURSE_ID', 'SCORE']
res_df = pd.DataFrame(res_dict, columns=['USER', 'COURSE_ID', 'SCORE'])

# Save the res_df DataFrame to a CSV file named "profile_rs_results.csv" without including the index
res_df.to_csv("profile_rs_results.csv", index=False)

# Output the res_df DataFrame
res_df

            USER   COURSE_ID  SCORE
0              2    ML0201EN   43.0
1              2  GPXX0ZG0EN   43.0
2              2  GPXX0Z2PEN   37.0
3              2    DX0106EN   47.0
4              2  GPXX06RFEN   52.0
...          ...         ...    ...
1500419  2102680  excourse62   15.0
1500420  2102680  excourse69   14.0
1500421  2102680  excourse77   14.0
1500422  2102680  excourse78   14.0
1500423  2102680  excourse79   14.0

[1500424 rows x 3 columns]

# **1. On average, how many new/unseen courses have been recommended to each user?**

In [44]:
# Average number of recommended courses per user
avg_courses = res_df.groupby('USER')['COURSE_ID'].count().mean()

print("Average recommended courses per test user:", avg_courses)

Average recommended courses per test user: 60.82471217772012

#**2. What are the most frequently recommended courses? Return the top-10 commonly recommended courses across all users?**

In [45]:
# Top 10 most frequently recommended courses
top10_courses = (
    res_df.groupby('COURSE_ID')
          .size()
          .reset_index(name='Recommendation_Count')
          .sort_values(by='Recommendation_Count', ascending=False)
          .head(10)
)

top10_courses

      COURSE_ID  Recommendation_Count
202    TA0106EN                 17390
230  excourse22                 15656
229  excourse21                 15656
111   GPXX0IBEN                 15644
173    ML0122EN                 15603
214  excourse06                 15062
212  excourse04                 15062
139  GPXX0TY1EN                 14689
280  excourse73                 14464
279  excourse72                 14464